"""Digest builder for shop / leaks aggregations.

A "digest" is one Telegram post that summarises multiple raw items in a
single, well-curated piece — useful when individual items don't score
high enough on their own (e.g. a single shop skin) but together they
make a strong post.

We build:
  * Daily shop digest — top 5 most relevant skins/bundles from today's
    Fortnite-API shop pull.
  * Weekly leaks digest — top 5 most-discussed leaks from the past 7
    days across all leak sources.

The digest body is generated by the LLM from a structured list of items
+ a digest-specific prompt. The banner is generated by the configured
image API.
"""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone
from typing import Iterable

from sqlalchemy import and_, select

from app.config import settings
from app.db.models import Post as PostORM, RawItem as RawItemORM
from app.db.session import get_session
from app.schemas import RawItem
from app.services.image_generator import ImageGenerator
from app.services.scoring import score_item
from app.services.verifier import get_leak_disclaimer
from app.services.writer import LLMClient

logger = logging.getLogger(__name__)


SHOP_DIGEST_SYSTEM = (
    "Ты редактор русскоязычного Telegram-канала о Fortnite. "
    "Пиши коротко, в официальном новостном стиле. "
    "Не используй кликбейт. Не выдавай утечки за официальные подтверждения."
)

SHOP_DIGEST_TEMPLATE = """🛒 <b>МАГАЗИН ФОРТНАЙТ СЕГОДНЯ</b>

Сегодня в магазине вернулись или появились новые предметы.

Главное:
{items}

{extras}

💎 Магазин для игроков: {shop_url}

#FortniteShop #МагазинФортнайт #Скины #VBucks"""

LEAKS_DIGEST_TEMPLATE = """🔥 <b>УТЕЧКИ НЕДЕЛИ</b> | Fortnite

За последние дни датамайнеры опубликовали несколько находок, которые могут указывать на будущий контент.

Главное:
{items}

{disclaimer}

💎 Магазин для игроков: {shop_url}

#FortniteLeaks #ФортнайтУтечки #Скины"""


def _row_to_rawitem(row: RawItemORM) -> RawItem:
    return RawItem(
        source=row.url or "unknown",
        source_level=1 if row.is_official else (3 if row.is_leak else 2),
        title=row.title or "",
        url=row.url or "",
        content=row.content or "",
        image_url=row.image_url or "",
        category=row.category or "general",
        published_at=row.published_at,
        is_official=bool(row.is_official),
        is_leak=bool(row.is_leak),
    )


# ---------------------------------------------------------------------------
# Common helpers
# ---------------------------------------------------------------------------


def _format_items_for_prompt(items: Iterable[RawItem], limit: int = 5) -> str:
    """Render top-N items as numbered bullet points."""
    lines: list[str] = []
    for idx, item in enumerate(items, start=1):
        if idx > limit:
            break
        title = item.title.strip()
        # Drop everything after a separator that's typically the rarity/type
        if " · " in title:
            title = title.split(" · ", 1)[0]
        lines.append(f"{idx}. {title}")
    return "\n".join(lines) if lines else "— подробности скоро"


async def _llm_polish(template: str, system: str = SHOP_DIGEST_SYSTEM) -> str:
    """Ask the LLM to polish a pre-rendered template into final post copy."""
    client = LLMClient()
    user_msg = (
        f"Перепиши этот пост в более естественном тоне русского "
        f"новостного стиля. Сохрани структуру, не выдумывай факты, "
        f"не добавляй ничего нового. Не оборачивай в markdown, верни "
        f"только готовый текст:\n\n{template}"
    )
    polished = await client.chat(
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user_msg},
        ],
        temperature=0.5,
        max_tokens=900,
    )
    return polished.strip() if polished else template


# ---------------------------------------------------------------------------
# Shop digest
# ---------------------------------------------------------------------------


async def build_shop_digest(
    *, dry_run: bool = False, top_n: int = 5
) -> dict:
    """Build today's shop digest. Returns a summary dict.

    Picks today's freshest Fortnite-API shop items, scores them
    individually, sorts by score descending, takes top_n, then
    generates a single combined post.
    """
    summary: dict = {
        "kind": "shop_digest",
        "candidates": 0,
        "selected": 0,
        "post_id": None,
        "image_path": None,
        "body_preview": "",
    }

    # naive UTC to match Postgres TIMESTAMP WITHOUT TIME ZONE
    cutoff = datetime.utcnow() - timedelta(hours=36)

    async with get_session() as session:
        stmt = (
            select(RawItemORM)
            .where(
                and_(
                    RawItemORM.created_at >= cutoff,
                    RawItemORM.url.like("%fortnite-api%shop%"),
                )
            )
            .order_by(RawItemORM.id.desc())
            .limit(80)
        )
        result = await session.execute(stmt)
        rows: list[RawItemORM] = list(result.scalars())

    summary["candidates"] = len(rows)
    if not rows:
        logger.info("Shop digest: no candidates")
        return summary

    # Score and pick top N
    scored: list[tuple[RawItem, int]] = []
    for row in rows:
        item = _row_to_rawitem(row)
        score = score_item(item)["total"]
        scored.append((item, score))
    scored.sort(key=lambda t: t[1], reverse=True)
    selected = [item for item, _ in scored[:top_n]]
    summary["selected"] = len(selected)
    if not selected:
        return summary

    # Build the digest body
    items_block = _format_items_for_prompt(selected, limit=top_n)
    base_text = SHOP_DIGEST_TEMPLATE.format(
        items=items_block,
        extras="",
        shop_url=settings.shop_url,
    )
    body = await _llm_polish(base_text)
    summary["body_preview"] = body[:300]

    # Banner with up to 4 reference images of real skins
    refs = [item.image_url for item in selected if item.image_url][:4]
    image_gen = ImageGenerator()
    image_path = await image_gen.generate_news_banner(
        topic="Fortnite item shop daily update featuring new and returning skins",
        headline="Магазин Fortnite сегодня",
        style="shop",
        reference_image_url=refs[0] if refs else None,
    )
    # Note: nano-banana-2 supports up to 14 references via image_input list,
    # but our generate_news_banner currently passes only one. Keeping it
    # simple here — the first ref usually carries enough Fortnite styling.
    summary["image_path"] = image_path

    if dry_run:
        return summary

    # Persist as a Post in pending_approval state (admin approval queue
    # will pick it up and forward to the admin for approve/reject).
    async with get_session() as session:
        post = PostORM(
            raw_item_id=None,
            title="Магазин Fortnite сегодня",
            body=body,
            image_prompt="shop digest",
            image_url=image_path or "",
            score=85,  # digests are inherently high-value
            status="pending_approval",
        )
        session.add(post)
        await session.flush()
        summary["post_id"] = post.id

    logger.info(
        "Shop digest queued for approval (post_id=%s, %d items)",
        summary["post_id"], summary["selected"],
    )
    return summary


# ---------------------------------------------------------------------------
# Leaks digest
# ---------------------------------------------------------------------------


async def build_leaks_digest(*, dry_run: bool = False, top_n: int = 5) -> dict:
    summary: dict = {
        "kind": "leaks_digest",
        "candidates": 0,
        "selected": 0,
        "post_id": None,
        "image_path": None,
        "body_preview": "",
    }

    # naive UTC to match Postgres TIMESTAMP WITHOUT TIME ZONE
    cutoff = datetime.utcnow() - timedelta(days=7)

    async with get_session() as session:
        stmt = (
            select(RawItemORM)
            .where(
                and_(
                    RawItemORM.created_at >= cutoff,
                    RawItemORM.is_leak.is_(True),
                )
            )
            .order_by(RawItemORM.id.desc())
            .limit(120)
        )
        result = await session.execute(stmt)
        rows: list[RawItemORM] = list(result.scalars())

    summary["candidates"] = len(rows)
    if not rows:
        return summary

    scored: list[tuple[RawItem, int]] = []
    seen_titles: set[str] = set()
    for row in rows:
        item = _row_to_rawitem(row)
        # Cheap dedup by title prefix to avoid 3 entries of "new skin leaked"
        key = item.title[:60].lower().strip()
        if key in seen_titles:
            continue
        seen_titles.add(key)
        score = score_item(item)["total"]
        scored.append((item, score))

    scored.sort(key=lambda t: t[1], reverse=True)
    selected = [item for item, _ in scored[:top_n]]
    summary["selected"] = len(selected)
    if not selected:
        return summary

    items_block = _format_items_for_prompt(selected, limit=top_n)
    base_text = LEAKS_DIGEST_TEMPLATE.format(
        items=items_block,
        disclaimer=get_leak_disclaimer(),
        shop_url=settings.shop_url,
    )
    body = await _llm_polish(base_text)
    summary["body_preview"] = body[:300]

    refs = [item.image_url for item in selected if item.image_url][:4]
    image_gen = ImageGenerator()
    image_path = await image_gen.generate_news_banner(
        topic="Fortnite leaked upcoming skins and cosmetics weekly roundup",
        headline="Утечки недели Fortnite",
        style="leak",
        reference_image_url=refs[0] if refs else None,
    )
    summary["image_path"] = image_path

    if dry_run:
        return summary

    async with get_session() as session:
        post = PostORM(
            raw_item_id=None,
            title="Утечки недели Fortnite",
            body=body,
            image_prompt="leaks digest",
            image_url=image_path or "",
            score=85,
            status="pending_approval",
        )
        session.add(post)
        await session.flush()
        summary["post_id"] = post.id

    logger.info(
        "Leaks digest queued for approval (post_id=%s, %d items)",
        summary["post_id"], summary["selected"],
    )
    return summary
